version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: unknown-frontend
    tty: true
    command: npm run start:prod
    env_file: ./env/prod.env
    ports:
      - 3000:3000
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    expose:
      - 3001

