version: '3.7'

services:
  mysql_db_container: 
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: unknown-backend
    command: npm run start:dev
    env_file: ./env/production.env
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src:/app/src
    expose:
      - 3001

volumes:
  mysql_db_data_container:
