version: '3.7'

services:
  db: 
    image: mysql:8.0
    container_name: unknow_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

